Algoritmo sitema_de_clasificacon_campeonato
	Definir partido Como Entero
	escribir "ingresa el resultado de un partido ganado,perdido o empatado";
	Leer partido
	p1<-partido>=10;
	p2<-partido>=5;
	escribir "en la tabla el equipo se posiciona  como",p1;
	Segun partido Hacer
		Caso 1: 
			escribir "en la tabla el equipo se posiciona  como primero",p1;
				Caso 2:
					escribir "en la tabla el equipo se posiciona  como segundo",p2;
			
		
		
	FinSegun
	
	
FinAlgoritmo
